workshops/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView, RedirectView
from workshops import models, views

urlpatterns = patterns('',
    # Workshop.
    url(r'^workshops/$',
        views.WorkshopListView.as_view(),
        name='workshops'),

    url(r'^workshop/$',
        views.WorkshopCreateView.as_view(),
        name='workshop_create'),

    url(r'^workshop/(?P<pk>\d+)/delete/$',
        views.WorkshopDeleteView.as_view(),
        name='workshop_delete'),

    url(r'^workshop/(?P<pk>\d+)/$',
        views.WorkshopDetailView.as_view(),
        name='workshop'),

    url(r'^workshop/(?P<pk>\d+)/edit/$',
        views.WorkshopUpdateView.as_view(),
        name='workshop_edit'),

    # Application.
    url(r'^workshop/(?P<workshop__pk>\d+)/apply/$',
        views.ApplicationCreateView.as_view(),
        name='apply'),

    url(r'^workshop/(?P<slug>\d+)/disapply/$',
        views.ApplicationDeleteView.as_view(),
        name='disapply'),

    url(r'^workshop/(?P<workshop__pk>\d+)/applications/$',
        views.ApplicationListView.as_view(),
        name='applications'),

    url(r'^workshop/(?P<workshop__pk>\d+)/application/(?P<pk>\d+)/$',
        views.ApplicationUpdateView.as_view(),
        name='application'),

    # Exercise.
    url(r'^workshop/(?P<workshop__pk>\d+)/newtask/$',
        views.ExerciseCreateView.as_view(),
        name='exercise_create'),

    url(r'^task/(?P<pk>\d+)/delete/$',
        views.ExerciseDeleteView.as_view(),
        name='exercise_delete'),

    url(r'^task/(?P<pk>\d+)/$',
        views.ExerciseDetailView.as_view(),
        name='exercise'),

    url(r'^task/(?P<pk>\d+)/edit/$',
        views.ExerciseUpdateView.as_view(),
        name='exercise_edit'),

    # Solution.
    url(r'task/(?P<exercise__pk>\d+)/solution/$',
        views.SolutionCreateUpdateView.as_view(),
        name='solution_update'),

    url(r'task/(?P<exercise__pk>\d+)/solution/(?P<pk>\d+)/$',
        views.SolutionGradeView.as_view(),
        name='solution_grade'),

    url(r'task/(?P<exercise__pk>\d+)/solutions/$',
        views.SolutionListView.as_view(),
        name='solutions'),

    # Person.
    url(r'^users/$',
        views.PersonListView.as_view(),
        name='people'),

    url(r'^user/(?P<slug>[a-zA-Z0-9-]+)/$',
        views.PersonDetailView.as_view(),
        name='person'),

    url(r'^$', RedirectView.as_view(
        url='/workshops'
    )),
)

www/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'www.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^login/$', 'django.contrib.auth.views.login',
    	{'template_name': 'workshops/login.html'}, name='login'),

    url(r'^logout/$', 'django.contrib.auth.views.logout',
    	name='logout'),

    url(r'', include('workshops.urls')),
)

workshops/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

shirtSizeChoices = ((0,'XXS'),(1,'XS'),(2,'S'),(3,'M'),
    (4,'L'),(5,'XL'),(6,'XXL'))

class Person(models.Model):
    user = models.OneToOneField(User)
    shirt_size = models.PositiveSmallIntegerField(
        max_length=3, choices=shirtSizeChoices, default=3)

    def __str__(self):
        if self.user.first_name and self.user.last_name:
            return self.user.first_name + ' ' + self.user.last_name
        else:
            return self.user.username

class Workshop(models.Model):
    name = models.CharField(max_length=30)
    host = models.ForeignKey(Person, related_name='workshop_host')
    text = models.TextField(max_length=5000)
    
    def __str__(self):
        return self.name

class Application(models.Model):
    person = models.ForeignKey(Person)
    workshop = models.ForeignKey(Workshop)
    qualified = models.BooleanField(default=False)

    def __str__(self):
        return '{0} - {1} ({2})'.format(
            self.person,
            self.workshop,
            self.qualified)

class Exercise(models.Model):
    name = models.CharField(max_length=30)
    text = models.TextField(max_length=3000)
    workshop = models.ForeignKey(Workshop)

    def __str__(self):
        return '{0} - {1}'.format(self.workshop, self.name)

class Solution(models.Model):
    application = models.ForeignKey(Application) #it already has a workshop in it
    exercise = models.ForeignKey(Exercise)
    text = models.TextField(max_length=5000)
    grade = models.PositiveSmallIntegerField(null=True, blank=True)

    def __str__(self):
        return '{0}: {1} - {2} ({3})'.format(
            self.application.workshop,
            self.exercise.name,
            self.application.person,
            self.grade)

workshops/views.py
from django import http
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from workshops import models

# Mixins.

class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

class OnlySelectedUsersMixin(LoginRequiredMixin):
    selectedUsers = tuple()

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, 'person') and (request.user.person in self.selectedUsers or kwargs.get('permit')):
            return super().dispatch(request, *args, **kwargs)
        raise PermissionDenied

class OnlySelectedUsersOrSuperuserMixin(OnlySelectedUsersMixin):
    def dispatch(self, request, *args, **kwargs):
        try:
            return super().dispatch(request, *args, **kwargs)
        except PermissionDenied:
            if request.user.is_superuser:
                return super().dispatch(request, *args, permit=True, **kwargs)
            raise PermissionDenied

class OnlyNotSelectedUsersMixin(LoginRequiredMixin):
    selectedUsers = tuple()

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, 'person') and not request.user.person in self.selectedUsers:
            return super().dispatch(request, *args, **kwargs)
        raise PermissionDenied

# Workshop.

class WorkshopListView(ListView):
    model = models.Workshop
    context_object_name = 'workshops_list'

class WorkshopCreateView(LoginRequiredMixin, CreateView):
    model = models.Workshop
    fields = ['name', 'text']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.host = self.request.user.person
        obj.save()
        return http.HttpResponseRedirect(reverse_lazy('workshop', args=(obj.pk,)))

class WorkshopUpdateView(OnlySelectedUsersOrSuperuserMixin, UpdateView):
    model = models.Workshop
    fields = ['name', 'text']

    def dispatch(self, request, *args, **kwargs):
        workshop = models.Workshop.objects.get(pk=self.kwargs['pk'])
        self.selectedUsers = (workshop.host,)
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('workshop', args=(self.kwargs['pk'],))

class WorkshopDeleteView(OnlySelectedUsersOrSuperuserMixin, DeleteView):
    model = models.Workshop
    success_url = reverse_lazy('workshops')

    def dispatch(self, request, *args, **kwargs):
        workshop = models.Workshop.objects.get(pk=self.kwargs['pk'])
        self.selectedUsers = (workshop.host,)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workshop'] = self.object
        return context

class WorkshopDetailView(DetailView):
    model = models.Workshop
    context_object_name = 'workshop'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated():
            currentUser = self.request.user.person
            objectOwner = self.object.host
            try:
                application = models.Application.objects.get(
                    workshop=self.object,person=currentUser)
            except models.Application.DoesNotExist:
                application = None
            context['isOwner'] = currentUser == objectOwner
            context['application'] = application

        context['applications'] = models.Application.objects.filter(workshop=self.object).order_by('-qualified')
        context['exercises'] = models.Exercise.objects.filter(workshop=self.object)
        return context

# Application.

class ApplicationCreateView(OnlyNotSelectedUsersMixin, CreateView):
    model = models.Application
    fields = []

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, 'person'):
            workshop = models.Workshop.objects.get(pk=self.kwargs['workshop__pk'])
            self.selectedUsers = (workshop.host,)
            currentUser = request.user.person
            
            try:
                application = models.Application.objects.get(
                    workshop=workshop,
                    person=currentUser)
            except models.Application.DoesNotExist:
                application = None

            if not application:
                return super().dispatch(request, *args, **kwargs)
        raise PermissionDenied

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workshop'] = models.Workshop.objects.get(pk=self.kwargs['workshop__pk'])
        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.workshop = models.Workshop.objects.get(
            pk=self.kwargs['workshop__pk'])
        obj.person = self.request.user.person
        obj.save()
        return http.HttpResponseRedirect(reverse_lazy('workshop', args=(self.kwargs['workshop__pk'],)))

class ApplicationDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Application
    slug_field = 'workshop__pk'

    def dispatch(self, request, *args, **kwargs):
        if self.get_object():
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def get_success_url(self):
        return reverse_lazy('workshop', args=(self.kwargs['slug'],))

    def get_object(self):
        if not hasattr(self, '_application'):
            try:
                self._application = models.Application.objects.get(
                    workshop__pk=self.kwargs['slug'],
                    person=self.request.user.person)
            except models.Application.DoesNotExist:
                self._application = None
        return self._application

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workshop'] = models.Workshop.objects.get(pk=self.kwargs['slug'])
        return context

class ApplicationListView(OnlySelectedUsersOrSuperuserMixin, ListView):
    model = models.Application
    context_object_name = 'applications_list'

    def dispatch(self, request, *args, **kwargs):
        self._workshop = models.Workshop.objects.get(pk=kwargs['workshop__pk'])
        self.selectedUsers = (self._workshop.host,)
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        try:
            queryset = models.Application.objects.filter(workshop__pk=self.kwargs['workshop__pk']).order_by('-qualified')
        except models.Solution.DoesNotExist:
            queryset = None
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workshop'] = self._workshop
        return context

class ApplicationUpdateView(OnlySelectedUsersOrSuperuserMixin, UpdateView):
    model = models.Application
    fields = ['qualified']
    context_object_name = 'application'
    template_name = 'workshops/application_detail.html'

    def dispatch(self, request, *args, **kwargs):
        self._workshop = models.Workshop.objects.get(pk=kwargs['workshop__pk'])
        application = models.Application.objects.get(pk=kwargs['pk'])
        self.selectedUsers = (self._workshop.host, application.person)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['solutions_list'] = models.Solution.objects.filter(application__pk=self.kwargs['pk'])
        except models.Solution.DoesNotExist:
            context['solutions_list'] = None
        return context

    def get_success_url(self):
        return reverse_lazy('applications', args=(self._workshop.pk,))

# Exercise.

class ExerciseCreateView(OnlySelectedUsersOrSuperuserMixin, CreateView):
    model = models.Exercise
    fields = ['name', 'text']

    def dispatch(self, request, *args, **kwargs):
        self._workshop = models.Workshop.objects.get(pk=self.kwargs['workshop__pk'])
        self.selectedUsers = (self._workshop.host,)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workshop'] = self._workshop
        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.workshop = models.Workshop.objects.get(
            pk=self.kwargs['workshop__pk'])
        obj.save()
        return http.HttpResponseRedirect(reverse_lazy('exercise', args=(obj.pk,)))

class ExerciseUpdateView(OnlySelectedUsersOrSuperuserMixin, UpdateView):
    model = models.Exercise
    fields = ['name', 'text']

    def dispatch(self, request, *args, **kwargs):
        self._exercise = models.Exercise.objects.get(pk=self.kwargs['pk'])
        self.selectedUsers = (self._exercise.workshop.host,)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workshop'] = self._exercise.workshop
        return context

    def get_success_url(self):
        return reverse_lazy('exercise', args=(self.kwargs['pk'],))

class ExerciseDeleteView(OnlySelectedUsersOrSuperuserMixin, DeleteView):
    model = models.Exercise

    def dispatch(self, request, *args, **kwargs):
        self._workshop = models.Exercise.objects.get(pk=kwargs['pk']).workshop
        self.selectedUsers = (self._workshop.host,)
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):

templates/workshops/application_confirm_delete.html
{% extends 'workshops/includes/base.html' %}

{% block content %}
	<form role="form" method="post" action="" class="form-horizontal text-center">
		{% csrf_token %}
		<p>Are you sure you want to disapply from <a href="{% url 'workshop' workshop.pk %}">{{ workshop.name }}</a> workshop?</p>
		</div>
		<div class="text-center">
			<button type="submit" class="btn btn-lg btn-success">Yes</button>
			<a href="{% url 'workshop' workshop.pk %}" class="btn btn-lg btn-danger">No</a>
		</div>
	</form>
{% endblock %}

templates/workshops/application_detail.html
{% extends 'workshops/includes/base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form role="form" method="post" action="">
		{% csrf_token %}
		<h2>{{ application.person }} - {{ application.workshop }}</h2>
		<div class="form-group">
			<label for="id_qualified">Qualified</label>
			{{ form.qualified }}
		</div>
		<button type="submit" class="btn btn-default">Submit</button>
		<hr>
		{% if solutions_list %}
			<p>Solutions:</p>
			<ul>
			{% for solution in solutions_list %}
				<li><a href="{% url 'solution_grade' solution.exercise.pk solution.pk %}">{{ solution.exercise.name }}</a> (grade: <strong>{{ solution.grade }}</strong>)</li>
			{% endfor %}
			</ul>
		{% else %}
			<p>That user haven't sent any solutions for your workshop.</p>
		{% endif %}
	</form>
{% endblock %}

templates/workshops/application_list.html
{% extends 'workshops/includes/base.html' %}

{% block content %}
	{% if applications_list %}
		<p class="lead">Applications for <a href="{% url 'workshop' workshop.pk %}">{{ workshop }}</a> workshop:</p>
		<table id="applications-table" class="table table-striped table-condensed">
			<thead>
				<th>Participant's name</th>
				<th>Link to application</th>
				<th>Qualified</th>
			</thead>
			<tbody>
			{% for application in applications_list %}
					<tr>
						<td><a href="{% url 'person' application.person.user.username %}">{{ application.person }}</a></td>
						<td><a href="{% url 'application' workshop.pk application.pk %}">application</td>
						<td><i class="pull-left glyphicon glyphicon-{% if application.qualified %}ok{% else %}remove{% endif %}"></i></td>
					</tr>
			{% endfor %}
			</tbody>
		</table>
	{% else %}
		<p class="lead">There are no applications for <a href="{% url 'workshop' workshop.pk %}">{{ workshop }}</a> workshop yet.</p>
	{% endif %}
{% endblock %}

templates/workshops/exercise_confirm_delete.html
{% extends 'workshops/includes/base.html' %}

{% block content %}
	<form role="form" method="post" action="" class="form-horizontal text-center">
		{% csrf_token %}
		<p>Are you sure you want to delete <a href="{% url 'exercise' exercise.pk %}">{{ exercise.name }}</a> task from <a href="{% url 'workshop' workshop.pk %}">{{ workshop }}</a> workshop?</p>
		</div>
		<div class="text-center">
			<button type="submit" class="btn btn-lg btn-success">Yes</button>
			<a href="{% url 'exercise' exercise.pk %}" class="btn btn-lg btn-danger">No</a>
		</div>
	</form>
{% endblock %}

templates/workshops/exercise_detail.html
{% extends 'workshops/includes/base.html' %}

{% block content %}
	<div id="exercise">
		<h2>{{ exercise.name }}</h2>
		<small>Workshop: <a href="{% url 'workshop' workshop.pk %}">{{ workshop }}</a></small><br>
		{% if application %}
		<small>{% if solution.grade %}Your grade: <strong>{{ solution.grade }}</strong>{% else %}You don't have any grade yet.{% endif %}</small>
		{% endif %}
		<br>
		{% if application %}
			<a href="{% url 'solution_update' exercise.pk %}" class="btn btn-info">Your solution</a>
		{% endif %}

		{% if not isOwner and not application %}
			<a href="{% url 'apply' workshop.pk %}" class="btn btn-warning">Apply for the workshop</a>
		{% endif %}

		{% if isOwner or user.is_superuser %}
			<a href="{% url 'solutions' exercise.pk %}" class="btn btn-info">List of solutions</a>
			<a href="{% url 'exercise_edit' exercise.pk %}" class="btn btn-warning">Edit</a>
			<a href="{% url 'exercise_delete' exercise.pk %}" class="btn btn-danger">Delete</a>
		{% endif %}
		<hr/>
		<p id="exercise-text">{{ exercise.text }}</p>
	</div>
{% endblock %}

templates/workshops/exercise_form.html
{% extends 'workshops/includes/base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form role="form" method="post" action="">
		{% csrf_token %}
		<p>New task for <a href="{% url 'workshop' workshop.pk %}">{{ workshop }}</a> workshop.</p>
		<div class="form-group">
			<label for="id_name">Task's name</label>
			{{ form.name | add_class:'form-control' | attr:'placeholder:Enter name' }}
		</div>
		<div class="form-group">
			<label for="id_text">Task's description</label>
			{{ form.text | add_class:'form-control' | attr:'rows:3' | attr:'placeholder:Enter description'}}
		</div>
		<button type="submit" class="btn btn-default">Submit</button>
	</form>
{% endblock %}

templates/workshops/login.html
{% extends 'workshops/includes/base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form class="form-signin" role="form" method="post" action="{% url 'django.contrib.auth.views.login' %}">
		{% csrf_token %}
		{% if form.errors %}
			<p class="warning">The username or password you entered is incorrect.</p>
		{% endif %}
		<h2 class="form-signin-heading">Sign in</h2>
		{{ form.username | add_class:'form-control' | attr:'placeholder:Username' | attr:'required autofocus' }}
		{{ form.password | add_class:'form-control' | attr:'placeholder:Password' | attr:'required' }}
		<button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
	</form>
{% endblock %}

templates/workshops/person_detail.html
{% extends 'workshops/includes/base.html' %}

{% block content %}
	<div id="person">
		<h2>{{ person }}</h2>
		<small id="person-text">T-Shirt size: <strong>{{ person.get_shirt_size_display }}</strong></small>
		<hr/>
		{% if host_workshops %}
		<div id="hosted">
		<p>Hosts workshops:</p>
		<ul>
			{% for workshop in host_workshops %}
				<li><a href="{% url 'workshop' workshop.pk %}">{{ workshop }}</a></li>
			{% endfor %}
		</ul>
		</div>
		{% else %}
		<p>Doesn't host any workshops.</p>
		{% endif %}
		<hr/>
		{% if applications %}
		<div id="applications">
		<p>Participates in workshops:</p>
		<ul>
			{% for application in applications %}
			<li>
				<a href="{% url 'workshop' application.workshop.pk %}">{{ application.workshop }}
				<i class="pull-left glyphicon glyphicon-{% if application.qualified %}ok{% else %}remove{% endif %}"></i>
				</a>
			</li>
			{% endfor %}
		</ul>
		</div>
		{% else %}
		<p>Doesn't participate in any workshops.</p>
		{% endif %}
	</div>
{% endblock %}

templates/workshops/person_list.html
{% extends 'workshops/includes/base.html' %}

{% block content %}
	{% if people_list %}
		<p class="lead">Users:</p>
		<div class="center-block">
		<ul>
			{% for person in people_list %}
			<li>
				<a href="{% url 'person' person.user.username %}">{{ person }}</a>
			</li>
			{% endfor %}
		</ul>
		</div>
	{% else %}
		<p class="lead">No users.</p>
	{% endif %}
{% endblock %}

templates/workshops/solution_form.html
{% extends 'workshops/includes/base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form role="form" method="post" action="">
		{% csrf_token %}
		<p>Your solution for <a href="{% url 'exercise' exercise.pk %}">{{ exercise }}</a> exercise:</p>
		<div class="form-group">
			{{ form.text | add_class:'form-control' | attr:'rows:10' | attr:'placeholder:Enter solution'}}
		</div>
		<button type="submit" class="btn btn-default">Submit</button>
	</form>
{% endblock %}

templates/workshops/workshop_confirm_delete.html
{% extends 'workshops/includes/base.html' %}

{% block content %}
	<form role="form" method="post" action="" class="form-horizontal text-center">
		{% csrf_token %}
		<p>Are you sure you want to delete <a href="{% url 'workshop' workshop.pk %}">{{ workshop.name }}</a> workshop?</p>
		</div>
		<div class="text-center">
			<button type="submit" class="btn btn-lg btn-success">Yes</button>
			<a href="{% url 'workshop' workshop.pk %}" class="btn btn-lg btn-danger">No</a>
		</div>
	</form>
{% endblock %}

templates/workshops/workshop_detail.html
{% extends 'workshops/includes/base.html' %}

{% block content %}
	<div id="workshop">
		<h2>{{ workshop }}</h2>
		<small>Host: <a href="{% url 'person' workshop.host.user.username %}">{{ workshop.host }}</a></small><br>
		{% if application %}
		<small>{% if application.qualified %}You've qualified for that workshop.{% else %}You've not qualified for that workshop yet.{% endif %}</small>
		{% endif %}
		<br>
		{% if user.is_authenticated %}
			{% if not isOwner %}
				{% if not application %}
					<a href="{% url 'apply' workshop.pk %}" class="btn btn-info">Apply</a>
				{% else %}
					<a href="{% url 'disapply' workshop.pk %}" class="btn btn-warning">Disapply</a>
				{% endif %}
			{% endif %}
			{% if isOwner or user.is_superuser %}
				<a href="{% url 'applications' workshop.pk %}" class="btn btn-info">Applications for that workshop</a>
				<a href="{% url 'workshop_edit' workshop.pk %}" class="btn btn-warning">Edit workshop</a>
				<a href="{% url 'workshop_delete' workshop.pk %}" class="btn btn-danger">Remove workshop</a>
			{% endif %}
		{% endif %}
		<hr>
		<p id="workshop-text">{{ workshop.text }}</p>
		<hr>

		{% if exercises %}
			<h4>Tasks for workshop:</h4>
			<ol>
				{% for exercise in exercises %}
				<li><a href="{% url 'exercise' exercise.pk %}">{{ exercise.name }}</a></li>
				{% endfor %}
			</ol>
			{% else %}
			<p>There are no tasks for that workshop yet.</p>
		{% endif %}

		{% if isOwner or user.is_superuser %}
			<a class="btn btn-default" href="{% url 'exercise_create' workshop.pk %}">Add new task</a>
		{% endif %}

		<hr>

		{% if applications %}
			<div id="applications">
				<h4>Participants applying for that workshop:</h4>
				<ul>
					{% for application in applications %}
					<li>
						<a href="{% url 'person' application.person.user.username %}">{{ application.person }}
						<i class="pull-left glyphicon glyphicon-{% if application.qualified %}ok{% else %}remove{% endif %}"></i>
						</a>
					</li>
					{% endfor %}
				</ul>
			</div>
		{% else %}
			<p>There are not participants applying for that workshop.</p>
		{% endif %}

	</div>
{% endblock %}

templates/workshops/workshop_form.html
{% extends 'workshops/includes/base.html' %}

{% load widget_tweaks %}

{% block content %}
	<form role="form" method="post" action="">
		{% csrf_token %}
		<div class="form-group">
			<label for="id_name">Workshop's name</label>
			{{ form.name | add_class:'form-control' | attr:'placeholder:Enter name' }}
		</div>
		<div class="form-group">
			<label for="id_text">Workshop's description</label>
			{{ form.text | add_class:'form-control' | attr:'rows:3' | attr:'placeholder:Enter description'}}
		</div>
		<button type="submit" class="btn btn-default">Submit</button>
	</form>
{% endblock %}

templates/workshops/workshop_list.html
{% extends 'workshops/includes/base.html' %}

{% block content %}
	{% if workshops_list %}
		<table id="workshops-table" class="table table-striped table-condensed">
			<thead>
				<tr>
					<th>Workshop's name</th>
					<th>Host</th>
				</tr>
			</thead>
			<tbody>
				{% for workshop in workshops_list %}
					<tr>
						<td><a href="{% url 'workshop' workshop.pk %}">{{ workshop }}</a></td>
						<td><a href="{% url 'person' workshop.host.user.username %}">{{ workshop.host }}</a></td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<p class="lead">No workshops.</p>
	{% endif %}
	{% if user.is_authenticated %}
		<a class="btn btn-default" href="{% url 'workshop_create' %}">Add new workshop</a>
	{% endif %}
{% endblock %}